const swaggerAutogen = require("swagger-autogen")({ openapi: "3.0.0" });

const options = {
    info: {
        title: "Cloud Engine API",
        version: "0.0.1",
        description:
            "These API endpoint documentations are autogenerated from the backend code.",
    },
    schemes: ["http"],
    securityDefinitions: {
        bearerAuth: {
            type: "http",
            scheme: "bearer",
            in: "header",
            bearerFormat: "JWT",
        },
    },
    tags: [
        {
            name: "Authentication",
            description: "These endpoints are used for user authentication.",
        },
        {
            name: "CDK",
            description:
                "These endpoints are in charge of interacting with AWS.",
        },
    ],
    definitions: {
        // These are sample model definitions.
        Parents: {
            father: "Simon Doe",
            mother: "Marie Doe",
        },
        User: {
            name: "Jhon Doe",
            age: 29,
            parents: {
                $ref: "#/definitions/Parents",
            },
            diplomas: [
                {
                    school: "XYZ University",
                    year: 2020,
                    completed: true,
                    internship: {
                        hours: 290,
                        location: "XYZ Company",
                    },
                },
            ],
        },
        AddUser: {
            $name: "Jhon Doe",
            $age: 29,
            about: "",
        },
    },
};
const outputFile = "./swagger-output.json";
const endpointsFiles = ["../server.js"];
swaggerAutogen(outputFile, endpointsFiles, options);
