name: Update Duplicate Repository

on:
  push:
    branches:
      - main  # or the appropriate branch name
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Update Duplicated Repository
        run: |
          git config --global user.email "mkim844@aucklanduni.ac.nz"
          git config --global user.name "521minsu"
          git clone https://github.com/uoa-compsci399-s2-2023/capstone-project-team-16.git
          git pull
          git remote add duplicated 'https://$GITHUB_TOKEN@github.com/521minsu/cloud-engine.git'
          git push duplicated main  # or the appropriate branch name
        env:
          GITHUB_TOKEN: ${{ secrets.MIRROR_TOKEN }}
