name: Update Duplicate Repository

on:
  push:
    branches:
      - main  # or the appropriate branch name
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Update Duplicated Repository
        run: |
          git clone https://github.com/uoa-compsci399-s2-2023/capstone-project-team-16.git
        env:
          GITHUB_TOKEN: ${{ secrets.MIRROR_TOKEN }}
