name: Update Duplicate Repository

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Update Duplicated Repository
        run: |
          # Configure user
          git config user.email "mkim844@aucklanduni.ac.nz"
          git config user.name "521minsu"

          # Set variables
          # SOURCE_DIR=$(PWD)  # Current working directory
          DEST_REPO_URL=https://$GITHUB_TOKEN@github.com/521minsu/cloud-engine.git  
          DEST_REPO_TOKEN=$GITHUB_TOKEN  


          # Clone destination repo
          git clone $DEST_REPO_URL destination-repo
          cd destination-repo

          # Copy source files to destination repo
          cp -R ../* .

          # Commit and push
          git add -A
          git commit -m "Automated commit from source repo"
          git push origin main  
        env:
          GITHUB_TOKEN: ${{ secrets.MIRROR_TOKEN }}
